blog_ish/urls.py
from django.conf.urls import url
from . import views


app_name = "blog"
urlpatterns = [
    
    #/blog
    url(r'^$', views.index, name='index'),
    
    #/blog/new
    url(r'^new/$', views.new_Post, name='new_Post'),
    
    #/blog/post_number
    url(r'^(?P<post_id>[0-9]+)/$', views.post, name='post'),
    
    #/blog/user_name/new-post
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name ='commnet'),
    
    #blog/posting
    url(r'^posting/$', views.posting, name='posting'),
    
    #blog/post_number/commenting
    url(r'^(?P<post_id>[0-9]+)/comment/$', views.comment, name ='comment'),
    
    #blog/post_number/commenting
    url(r'^(?P<post_id>[0-9]+)/commenting/$', views.commenting, name ='commenting'),
]

final_project/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^blog/', include('blog_ish.urls')),
]

blog_ish/models.py
from __future__ import unicode_literals
from datetime import datetime
from django.db import models

class PostManager(models.Manager):
    def create_post(self, post_text):
        post = self.create(post_text=post_text, date_published=datetime.now())
        return post
        
class Post(models.Model):
    post_text = models.CharField(max_length=500)
    date_published = models.DateTimeField('date published')
    
    objects = PostManager()
    
    def __str__(self):
        return self.post_text
        
class CommentManager(models.Manager):
    def create_comment(self, post, comment_text):
        comment = self.create(post=post, comment_text=comment_text, date_published=datetime.now())
        return comment
        
class Comment(models.Model):
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    comment_text = models.CharField(max_length=500)
    date_published = models.DateTimeField('date published')
    
    objects = CommentManager()
    
    def __str__(self):
        return self.comment_text


# Create your models here.

blog_ish/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponse, HttpResponseRedirect
from django.template import loader
from .models import Post, Comment
from django.core.urlresolvers import reverse


def index(request):
    latest_blog_posts = Post.objects.order_by('-date_published')[:10]
    template = loader.get_template('blog_ish/index.html')
    context = {
        'latest_blog_posts': latest_blog_posts,
    }
    return HttpResponse(template.render(context, request))

def new_Post(request):
    template = loader.get_template('blog_ish/newPost.html')
    context = {}
    return HttpResponse(template.render(context,request))

def post(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog_ish/post.html', {'post': post})

def posting(request):
    post = Post.objects.create_post(request.POST.get('post', request.GET['post']))
    post.save()
    return HttpResponseRedirect(reverse('blog:index'))
    
def comment(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    return render(request, 'blog_ish/comment.html', {'post': post})

def commenting(request, post_id):
    post = get_object_or_404(Post, pk=post_id)
    comment = Comment.objects.create_comment(post, request.POST.get('comment', request.GET['comment']))
    comment.save()
    return HttpResponseRedirect(reverse('blog:post', args=(post.id,)))


# Create your views here.

blog_ish/templates/blog_ish/comment.html
<!DOCTYPE html>
<html>
    <head>
        <meta charset="utf-8"> {% load staticfiles %}
        <link rel="stylesheet" type="text/css" href="{% static 'blog_ish/style.css' %}" />
    
        <title>Make a Comment</title>
    </head>
    <body>
        <h1>Add a Comment!</h1>

        <a href="{% url 'blog:index' %}" ><button type="button" class="home">Back to Home~</button></a></button>

        <div class='Post'>
            <a href="{% url 'blog:post' post.id %}">
            <p>
                {{ post.post_text }}
            </p>
            </a>
        </div>

        <br>

        <div class="Submission">
            <form action="{% url 'blog:commenting' post.id %}">
            {% csrf_token %}
            <br>
    
            Comment: <br>
            <input type="text" name="comment" maxlength="500" id='comment' autofocus> <br> <br>

    
            <input type="submit" value="Submit" id="submit">
    
    
            </form>
        </div>
    </body>
</html>

blog_ish/templates/blog_ish/index.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"> {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog_ish/style.css' %}" />
    <script  type="text/javascript" src="{% static 'blog_ish/javascript.js' %}"></script>
    <title>Beach Blog!</title>
</head>

<body>
    <h1>Welcome to the Beach Blog!</h1>
    
     <button type="button" class="home" onclick="doSomething(this)">JavaScript</button>
    
    <a href="{% url 'blog:new_Post' %}"><button type="button">Add a Post!</button></a></button>
    <br> {% if latest_blog_posts %} {% for post in latest_blog_posts %}
    <br>
    <div class="Post">
        <a href="/blog/{{ post.id }}/">
            <p>{{ post.post_text }}</p>
        </a>
    </div>
    {% endfor %} {% else %}
    <div class="Post">
        <p>No posts are available.</p>
    </div>
    {% endif %}

</body>

</html>

blog_ish/templates/blog_ish/newPost.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"> {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog_ish/style.css' %}" />

    <title>Make a Post</title>
</head>

<body>
    <h1>Time for a post</h1>

    <a href="{% url 'blog:index' %}"><button type="button"  class="home">Back to Home~</button></a></button>

    <div class="Submission">
        <form action={% url 'blog:posting' %}>
            {% csrf_token %} Post: <br>
            <input type="text" name="post" maxlength="50" id='post' autofocus> <br> <br>


            <input type="submit" value="Submit" id='submit'>
        </form>

    </div>
</body>

</html>

blog_ish/templates/blog_ish/post.html
<!DOCTYPE html>
<html>

<head>
    <meta charset="utf-8"> {% load staticfiles %}
    <link rel="stylesheet" type="text/css" href="{% static 'blog_ish/style.css' %}" />

    <title>It's a Post</title>
</head>

<body>
    <h1>Aloha! It's a post! </h1>

    <a href="{% url 'blog:index' %}"><button type="button"  class="home">Back to Home~</button></a></button>

    <div class="Post">
        <p>
            {{ post.post_text }}
        </p>

        {% for comment in post.comment_set.all %}
        <br>
        <div class="Comment">
            <p>{{ comment.comment_text }}</p>
        </div>
        {% endfor %}

    </div>

    <br>
    <a href="{% url 'blog:comment' post.id %}"><button type="button">Add a Comment!</button></a></button>
</body>

</html>